# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

builds:
  - id: dx
    main: ./cmd/dx/dx.go
    binary: dx
    ldflags:
      - -X github.com/plumming/dx/pkg/version.Version={{.Version}} -X github.com/plumming/dx/pkg/version.Revision={{.ShortCommit}} -X github.com/plumming/dx/pkg/version.BuildDate={{.CommitDate}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
  - id: dx-windows-amd64
    main: ./cmd/dx/dx.go
    binary: dx
    ldflags:
      - -X github.com/plumming/dx/pkg/version.Version={{.Version}} -X github.com/plumming/dx/pkg/version.Revision={{.ShortCommit}} -X github.com/plumming/dx/pkg/version.BuildDate={{.CommitDate}}
    goos:
      - windows
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
  algorithm: sha256

changelog:
  disable: false

release:
  draft: false
  prerelease: false
  name_template: "{{.Tag}}"

brews:
  - name: dx
    repository:
      owner: plumming
      name: homebrew-tap
      token: "{{ .Env.CHILLY_TAP_TOKEN }}"
    commit_author:
      name: garethjevans
      email: gareth@bryncynfelin.co.uk
    directory: Formula
    caveats: "How to use this binary"
    description: "Have you got the chillys?"
