// Code generated by counterfeiter. DO NOT EDIT.
package prompterfakes

import (
	"sync"

	"github.com/plumming/dx/pkg/prompter"
)

type FakePrompter struct {
	SelectFromOptionsStub        func(string, []string) (string, error)
	selectFromOptionsMutex       sync.RWMutex
	selectFromOptionsArgsForCall []struct {
		arg1 string
		arg2 []string
	}
	selectFromOptionsReturns struct {
		result1 string
		result2 error
	}
	selectFromOptionsReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePrompter) SelectFromOptions(arg1 string, arg2 []string) (string, error) {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.selectFromOptionsMutex.Lock()
	ret, specificReturn := fake.selectFromOptionsReturnsOnCall[len(fake.selectFromOptionsArgsForCall)]
	fake.selectFromOptionsArgsForCall = append(fake.selectFromOptionsArgsForCall, struct {
		arg1 string
		arg2 []string
	}{arg1, arg2Copy})
	stub := fake.SelectFromOptionsStub
	fakeReturns := fake.selectFromOptionsReturns
	fake.recordInvocation("SelectFromOptions", []interface{}{arg1, arg2Copy})
	fake.selectFromOptionsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePrompter) SelectFromOptionsCallCount() int {
	fake.selectFromOptionsMutex.RLock()
	defer fake.selectFromOptionsMutex.RUnlock()
	return len(fake.selectFromOptionsArgsForCall)
}

func (fake *FakePrompter) SelectFromOptionsCalls(stub func(string, []string) (string, error)) {
	fake.selectFromOptionsMutex.Lock()
	defer fake.selectFromOptionsMutex.Unlock()
	fake.SelectFromOptionsStub = stub
}

func (fake *FakePrompter) SelectFromOptionsArgsForCall(i int) (string, []string) {
	fake.selectFromOptionsMutex.RLock()
	defer fake.selectFromOptionsMutex.RUnlock()
	argsForCall := fake.selectFromOptionsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePrompter) SelectFromOptionsReturns(result1 string, result2 error) {
	fake.selectFromOptionsMutex.Lock()
	defer fake.selectFromOptionsMutex.Unlock()
	fake.SelectFromOptionsStub = nil
	fake.selectFromOptionsReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) SelectFromOptionsReturnsOnCall(i int, result1 string, result2 error) {
	fake.selectFromOptionsMutex.Lock()
	defer fake.selectFromOptionsMutex.Unlock()
	fake.SelectFromOptionsStub = nil
	if fake.selectFromOptionsReturnsOnCall == nil {
		fake.selectFromOptionsReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.selectFromOptionsReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.selectFromOptionsMutex.RLock()
	defer fake.selectFromOptionsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePrompter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ prompter.Prompter = new(FakePrompter)
